module.exports = {
    ACCOUNT_CREATED: 1,
    FORGOT_PASSWORD: 2,
    ACCOUNT_UPDATED: 3,
    DELETE_ACCOUNT_USER: 4,
    DELETE_ACCOUNT_ADMIN: 5,
    USER_IS_LOGGED: 5,
    CHANGE_PASSWORD: 6,
    ACCOUNT_ACTIVATED: 7
};
